version: "3.9"

services:
  serv_1_web:
    build: ./service_1
    container_name: serv_1_web
    ports:
      - "8000:5000"

  serv_2_web:
    build: ./service_2
    container_name: serv_2_web
    ports:
      - "8001:5000"
    networks:
      - mongodb_network

  serv_3_web:
    build: ./service_3/app
    container_name: serv_3_web
    ports:
      - "8002:5000"
    networks:
      - rabbitmq_network

  receiver:
    build: ./service_3/receiver
    container_name: receiver
    networks:
      - rabbitmq_network
      - mongodb_network

  mongodb:
    image: mongo:4.2
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=artem
      - MONGO_INITDB_ROOT_PASSWORD=0000
    volumes:
      - ./db:/data/db
      - ./service_2/docker-entrypoint-initdb.d/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
    networks:
      - mongodb_network
    ports:
      - 27017:27017
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo 10.10.10.60:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped

  rabbitmq:
    image: 'rabbitmq:3.11'
    container_name: rabbitmq
    ports:
      - '5672:5672'
    networks:
      - mongodb_network
      - rabbitmq_network

networks:
  mongodb_network:
    external: false
  rabbitmq_network:
    external: false
