version: "3.8"
services:
  mongodb:
    image: mongo:4.2
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=artem
      - MONGO_INITDB_ROOT_PASSWORD=0000
    volumes:
      - ./db:/data/db
    networks:
      - mongodb_network
    ports:
      - 27017:27017
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo 10.10.10.60:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped

networks:
  mongodb_network:
    external: false
